### ISSUE TITLE
Not more than 5kph with VCA-mod in MP

### ISSUE THREAD

**Issue by TobiasGesch** [yumi-modding/FS22_CombineXP#39] opened 2022-10-17 18:28 UTC
**Describe the bug**
I´m using VCA mod, Realism addons and the Italia map on a dedicated MP server.
no matter which combination i use (Combine/Cutter) VCA in "KeepSpeed"-Mode will only let me go up to 5kph completely without recognizing the yield. This also happens if i lift the cutter and therefore not Harvesting at all. It will let me drive the speed according to the yield/Combine/Cutter combination as soon as i don´t use VCAs keepSpeed. As soon as i disable the Engine Power Limit i can go above 5kph (but obviously without the automatic speed adjustment). I only have this Problem on the MP Server, with the same mods it works fine in SP.

**To Reproduce**
Details to reproduce the behavior:
- Harvested crop: Any
- Combine and cutter: Any (For example: NewHolland CH7.70 with Varifeed 28Ft)
- Yield: Any
- Seasons is active
- Time of the day when harvesting: Any

**Additional context**
It definitely looks like a mod conflict but maybe you can still spot something.
I attached the Server-Log but it shows no Errors (Only missing .wav files from the map, which was just a sound file)
[log.txt](https://github.com/yumi-modding/FS22_CombineXP/files/9803469/log.txt)

**Comment by yumi-modding** [comment] 2022-10-17 18:58
Thanks for this detailled feedback. I will try ro reproduce and let you know if i need more info.

**Comment by Watabane** [comment] 2023-03-08 20:49
Hello, 

I'm running a very similar setup (VCA and things like that) and I'm also stuck at 5kph. It would make a nice combinaison as we can precisely ajust the speed with this mod to optimise the load of the machine.
 
Hope this will help !

**Comment by Tubezki** [comment] 2023-04-11 20:34
Yea this issue still exists for us who use these mods and there are plenty playing with the same mods. It only affects in multiplayer and not the save game owner but anyone else who joins to the same game has low speed when combining and using VCA with "KEEP SPEED" Option.

**Comment by Tubezki** [comment] 2023-09-03 16:03
I think Yumi might be dead and not supporting this mod anymore? its been months and still people talking about this in the giants forums and also on reddit :S I hope we get this fixed soon.

**Comment by TobiasGesch** [comment] 2023-09-03 17:34
That would be really sad... it's such a great mod and adds so much to the realism. I'd even be happy to provide a test server for him since I'm already running one with some friends. Seems to be a dedicated server-only problem, it works just fine if you host it locally

**Comment by yumi-modding** [comment] 2023-09-03 18:19
Hello
I'm still there but not really active on modding this year.
If you can provide dedi server access that could help yes. I can share a mod ZIP with more traces so I can analyze the issue more easily. You can contact me on discord (yumi_modding) to share this

**Comment by yumi-modding** [comment] 2023-09-04 08:32
Thanks @TobiasGesch for providing inputs to reproduce the issue. I could experience it on the server you shared.
Now I need to see how I can support this behavior and fix the issue.

**Comment by yumi-modding** [comment] 2023-09-18 11:24
Hello
It looks like I have found a fix for this issue.
I will soon request an update on modhub so everyone can use it.

**Closed as completed** 2023-09-22 10:17 UTC
